USE tienda_alquemia;
SET NAMES 'utf8mb4';

INSERT INTO categorias (nombre) VALUES ('shop-the-look');
INSERT INTO categorias (nombre) VALUES ('vestidos-y-monos');
INSERT INTO categorias (nombre) VALUES ('camisetas-y-tops');
INSERT INTO categorias (nombre) VALUES ('camisetas');
INSERT INTO categorias (nombre) VALUES ('faldas');
INSERT INTO categorias (nombre) VALUES ('jerseis');
INSERT INTO categorias (nombre) VALUES ('camisas');
INSERT INTO categorias (nombre) VALUES ('polos');
INSERT INTO categorias (nombre) VALUES ('intimo');
INSERT INTO categorias (nombre) VALUES ('complementos');
INSERT INTO categorias (nombre) VALUES ('pantalones');
INSERT INTO categorias (nombre) VALUES ('chaquetas');
INSERT INTO categorias (nombre) VALUES ('blusas-y-camisas');
INSERT INTO categorias (nombre) VALUES ('zapatos');
INSERT INTO categorias (nombre) VALUES ('vaqueros');
INSERT INTO categorias (nombre) VALUES ('chaquetas-y-cazadoras');
INSERT INTO categorias (nombre) VALUES ('sudaderas');
INSERT INTO categorias (nombre) VALUES ('americanas');
INSERT INTO categorias (nombre) VALUES ('abrigos');
